import { Router } from 'express';
import { v4 as uuidv4 } from 'uuid';
import db from '../db/index.js';
import { authMiddleware } from '../middleware/auth.js';
import { PARTS_CATALOG, ZONE_PARTS } from '../services/partsCatalog.js';
const router = Router({ mergeParams: true });
router.use(authMiddleware as any);
function getCat(zone: string): string { if (zone.includes('Headlight') || zone.includes('Taillight')) return 'Lighting'; if (zone.includes('Door')) return 'Doors'; if (zone.includes('Fender') || zone.includes('Mirror')) return 'Sides'; if (zone.includes('Quarter') || zone.includes('Rocker')) return 'Sides'; if (zone.includes('Bumper') || zone.includes('Hood') || zone.includes('Grille')) return 'Front'; if (zone.includes('Liftgate') || zone.includes('Trunk')) return 'Rear'; if (zone.includes('Windshield') || zone.includes('Roof')) return 'Glass'; if (zone.includes('Wheel')) return 'Wheels'; return 'Structural'; }
router.post('/:zone', (req: any, res) => { const vid = req.params.id; const zone = req.params.zone; const v = db.prepare('SELECT 1 FROM vehicles WHERE id = ? AND user_id = ?').get(vid, req.userId); if (!v) { res.status(404).json({ error: 'Not found' }); return; } const existing = db.prepare('SELECT * FROM damage_items WHERE vehicle_id = ? AND zone = ?').get(vid, zone); if (existing) { db.prepare('DELETE FROM damage_items WHERE vehicle_id = ? AND zone = ?').run(vid, zone); const pids = ZONE_PARTS[zone] || []; for (const pid of pids) db.prepare('DELETE FROM repair_items WHERE vehicle_id = ? AND part_id = ?').run(vid, pid); res.json({ added: false, zone }); } else { const partIds = ZONE_PARTS[zone] || []; const estCost = partIds.reduce((s, pid) => s + (PARTS_CATALOG[pid]?.price || 0), 0); db.prepare('INSERT INTO damage_items (id, vehicle_id, zone, category, severity, description, estimated_cost) VALUES (?, ?, ?, ?, ?, ?, ?)').run(uuidv4(), vid, zone, getCat(zone), 'moderate', `${zone} damage detected`, estCost); for (const pid of partIds) { const cp = PARTS_CATALOG[pid]; if (!cp) continue; db.prepare(`INSERT INTO repair_items (id, vehicle_id, part_id, name, category, description, estimated_cost, quantity, override_price, selected, purchased, repairable) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, 1, 0, ?)`).run(uuidv4(), vid, pid, cp.name, cp.category, `Replace ${cp.name}`, cp.price, 1, cp.repairable ? 1 : 0); } res.json({ added: true, zone, partsAdded: partIds.length }); } });
router.get('/', (req: any, res) => { const items = db.prepare('SELECT * FROM damage_items WHERE vehicle_id = ?').all(req.params.id); res.json(items); });
export default router;
