export const PARTS_CATALOG: Record<string, { name: string; category: string; price: number; repairable: boolean }> = {
  'hood': { name: 'Hood', category: 'Front', price: 280, repairable: true },
  'hood-hinge': { name: 'Hood Hinge', category: 'Front', price: 45, repairable: false },
  'hood-latch': { name: 'Hood Latch', category: 'Front', price: 35, repairable: false },
  'front-bumper': { name: 'Front Bumper', category: 'Front', price: 320, repairable: true },
  'bumper-reinf': { name: 'Bumper Reinforcement', category: 'Front', price: 120, repairable: false },
  'bumper-absorber': { name: 'Bumper Absorber', category: 'Front', price: 65, repairable: false },
  'bumper-bracket-l': { name: 'Bumper Bracket - Left', category: 'Front', price: 28, repairable: false },
  'bumper-bracket-r': { name: 'Bumper Bracket - Right', category: 'Front', price: 28, repairable: false },
  'headlight-l': { name: 'Headlight Assembly - Left', category: 'Lighting', price: 245, repairable: false },
  'headlight-r': { name: 'Headlight Assembly - Right', category: 'Lighting', price: 245, repairable: false },
  'headlight-bracket-l': { name: 'Headlight Bracket - Left', category: 'Lighting', price: 38, repairable: false },
  'headlight-bracket-r': { name: 'Headlight Bracket - Right', category: 'Lighting', price: 38, repairable: false },
  'grille': { name: 'Grille', category: 'Front', price: 185, repairable: true },
  'grille-molding': { name: 'Grille Molding', category: 'Front', price: 55, repairable: false },
  'fender-l': { name: 'Fender - Left', category: 'Sides', price: 265, repairable: true },
  'fender-r': { name: 'Fender - Right', category: 'Sides', price: 265, repairable: true },
  'fender-liner-l': { name: 'Fender Liner - Left', category: 'Sides', price: 42, repairable: false },
  'fender-liner-r': { name: 'Fender Liner - Right', category: 'Sides', price: 42, repairable: false },
  'windshield': { name: 'Windshield', category: 'Glass', price: 380, repairable: false },
  'door-lf': { name: 'Door - Left Front', category: 'Doors', price: 420, repairable: true },
  'door-rf': { name: 'Door - Right Front', category: 'Doors', price: 420, repairable: true },
  'door-lr': { name: 'Door - Left Rear', category: 'Doors', price: 395, repairable: true },
  'door-rr': { name: 'Door - Right Rear', category: 'Doors', price: 395, repairable: true },
  'door-handle-lf': { name: 'Door Handle - LF', category: 'Doors', price: 48, repairable: false },
  'door-handle-rf': { name: 'Door Handle - RF', category: 'Doors', price: 48, repairable: false },
  'door-handle-lr': { name: 'Door Handle - LR', category: 'Doors', price: 48, repairable: false },
  'door-handle-rr': { name: 'Door Handle - RR', category: 'Doors', price: 48, repairable: false },
  'door-glass-lf': { name: 'Door Glass - LF', category: 'Glass', price: 165, repairable: false },
  'door-glass-rf': { name: 'Door Glass - RF', category: 'Glass', price: 165, repairable: false },
  'door-glass-lr': { name: 'Door Glass - LR', category: 'Glass', price: 155, repairable: false },
  'door-glass-rr': { name: 'Door Glass - RR', category: 'Glass', price: 155, repairable: false },
  'door-molding-lf': { name: 'Door Molding - LF', category: 'Doors', price: 35, repairable: false },
  'door-molding-rf': { name: 'Door Molding - RF', category: 'Doors', price: 35, repairable: false },
  'quarter-l': { name: 'Quarter Panel - Left', category: 'Sides', price: 380, repairable: true },
  'quarter-r': { name: 'Quarter Panel - Right', category: 'Sides', price: 380, repairable: true },
  'quarter-glass-l': { name: 'Quarter Glass - Left', category: 'Glass', price: 125, repairable: false },
  'quarter-glass-r': { name: 'Quarter Glass - Right', category: 'Glass', price: 125, repairable: false },
  'rocker-l': { name: 'Rocker Panel - Left', category: 'Sides', price: 165, repairable: true },
  'rocker-r': { name: 'Rocker Panel - Right', category: 'Sides', price: 165, repairable: true },
  'roof-panel': { name: 'Roof Panel', category: 'Roof', price: 520, repairable: true },
  'roof-rail-l': { name: 'Roof Rail - Left', category: 'Roof', price: 85, repairable: false },
  'roof-rail-r': { name: 'Roof Rail - Right', category: 'Roof', price: 85, repairable: false },
  'mirror-l': { name: 'Side Mirror - Left', category: 'Sides', price: 195, repairable: true },
  'mirror-r': { name: 'Side Mirror - Right', category: 'Sides', price: 195, repairable: true },
  'taillight-l': { name: 'Taillight - Left', category: 'Lighting', price: 185, repairable: false },
  'taillight-r': { name: 'Taillight - Right', category: 'Lighting', price: 185, repairable: false },
  'rear-bumper': { name: 'Rear Bumper', category: 'Rear', price: 285, repairable: true },
  'bumper-reinf-rear': { name: 'Rear Bumper Reinforcement', category: 'Rear', price: 95, repairable: false },
  'liftgate': { name: 'Liftgate/Trunk Lid', category: 'Rear', price: 450, repairable: true },
  'liftglass': { name: 'Liftgate Glass', category: 'Glass', price: 225, repairable: false },
  'wheel-lf': { name: 'Wheel - LF', category: 'Wheels', price: 180, repairable: false },
  'wheel-rf': { name: 'Wheel - RF', category: 'Wheels', price: 180, repairable: false },
  'wheel-lr': { name: 'Wheel - LR', category: 'Wheels', price: 180, repairable: false },
  'wheel-rr': { name: 'Wheel - RR', category: 'Wheels', price: 180, repairable: false },
};

export const ZONE_PARTS: Record<string, string[]> = {
  'Hood': ['hood', 'hood-hinge', 'hood-latch'],
  'Bumper': ['front-bumper', 'bumper-reinf', 'bumper-absorber', 'bumper-bracket-l', 'bumper-bracket-r'],
  'Left Headlight': ['headlight-l', 'headlight-bracket-l'],
  'Right Headlight': ['headlight-r', 'headlight-bracket-r'],
  'Grille': ['grille', 'grille-molding'],
  'Left Fender': ['fender-l', 'fender-liner-l'],
  'Right Fender': ['fender-r', 'fender-liner-r'],
  'Windshield': ['windshield'],
  'Left Door': ['door-lf', 'door-handle-lf', 'door-glass-lf', 'door-molding-lf'],
  'Right Door': ['door-rf', 'door-handle-rf', 'door-glass-rf', 'door-molding-rf'],
  'Left Rear Door': ['door-lr', 'door-handle-lr', 'door-glass-lr'],
  'Right Rear Door': ['door-rr', 'door-handle-rr', 'door-glass-rr'],
  'Left Quarter Panel': ['quarter-l', 'quarter-glass-l'],
  'Right Quarter Panel': ['quarter-r', 'quarter-glass-r'],
  'Left Rocker': ['rocker-l'],
  'Right Rocker': ['rocker-r'],
  'Roof': ['roof-panel', 'roof-rail-l', 'roof-rail-r'],
  'Left Mirror': ['mirror-l'],
  'Right Mirror': ['mirror-r'],
  'Left Taillight': ['taillight-l'],
  'Right Taillight': ['taillight-r'],
  'Rear Bumper': ['rear-bumper', 'bumper-reinf-rear'],
  'Trunk/Liftgate': ['liftgate', 'liftglass'],
  'Wheels': ['wheel-lf', 'wheel-rf', 'wheel-lr', 'wheel-rr'],
};
