import db from './index.js';
const tables = [
  `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, name TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS vehicles (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, vin TEXT NOT NULL, year INTEGER DEFAULT 0, make TEXT DEFAULT '', model TEXT DEFAULT '', trim TEXT DEFAULT '', mileage INTEGER DEFAULT 0, engine TEXT DEFAULT '', transmission TEXT DEFAULT '', drivetrain TEXT DEFAULT '', body_class TEXT DEFAULT '', fuel_type TEXT DEFAULT '', title_status TEXT DEFAULT 'Salvage', exterior_color TEXT DEFAULT '', is_active INTEGER DEFAULT 0, profit_goal_type TEXT DEFAULT 'fixed', profit_goal_value INTEGER DEFAULT 5000, contingency_percent INTEGER DEFAULT 10, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS damage_items (id TEXT PRIMARY KEY, vehicle_id TEXT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE, zone TEXT NOT NULL, category TEXT DEFAULT '', severity TEXT DEFAULT 'moderate', description TEXT DEFAULT '', estimated_cost INTEGER DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS repair_items (id TEXT PRIMARY KEY, vehicle_id TEXT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE, part_id TEXT DEFAULT '', name TEXT DEFAULT '', category TEXT DEFAULT '', description TEXT DEFAULT '', estimated_cost INTEGER DEFAULT 0, quantity INTEGER DEFAULT 1, override_price INTEGER, selected INTEGER DEFAULT 1, purchased INTEGER DEFAULT 0, repairable INTEGER DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS repair_estimates (vehicle_id TEXT PRIMARY KEY REFERENCES vehicles(id) ON DELETE CASCADE, use_detailed INTEGER DEFAULT 1, use_total_override INTEGER DEFAULT 0, total_override INTEGER DEFAULT 0, body_labor_hours INTEGER DEFAULT 0, body_labor_rate INTEGER DEFAULT 65, paint_labor_hours INTEGER DEFAULT 0, paint_labor_rate INTEGER DEFAULT 55, mech_labor_hours INTEGER DEFAULT 0, mech_labor_rate INTEGER DEFAULT 85, frame_labor_hours INTEGER DEFAULT 0, frame_labor_rate INTEGER DEFAULT 95, paint_materials INTEGER DEFAULT 0, shop_supplies INTEGER DEFAULT 0, alignment_cost INTEGER DEFAULT 0, adas_calibration INTEGER DEFAULT 0, misc_cost INTEGER DEFAULT 0, transport_cost INTEGER DEFAULT 0, other_cost INTEGER DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS comparables (id TEXT PRIMARY KEY, vehicle_id TEXT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE, source TEXT DEFAULT '', year INTEGER DEFAULT 0, make TEXT DEFAULT '', model TEXT DEFAULT '', trim TEXT DEFAULT '', mileage INTEGER DEFAULT 0, price INTEGER DEFAULT 0, title_status TEXT DEFAULT 'clean', location TEXT DEFAULT '', url TEXT DEFAULT '', listed_date TEXT DEFAULT '')`,
  `CREATE INDEX IF NOT EXISTS idx_vehicles_user ON vehicles(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_damage_vehicle ON damage_items(vehicle_id)`,
  `CREATE INDEX IF NOT EXISTS idx_repairs_vehicle ON repair_items(vehicle_id)`,
  `CREATE INDEX IF NOT EXISTS idx_comparables_vehicle ON comparables(vehicle_id)`,
];
for (const sql of tables) db.exec(sql);
console.log('Database initialized');
